import os
import pyperclip

def generate_folder_tree(folder_path, indent=""):
    """
    Recursively generates the folder tree structure with names and files.

    Parameters:
        folder_path (str): Path to the folder.
        indent (str): Indentation for displaying the tree structure.

    Returns:
        list: A list of tuples where each tuple contains the type ("Folder" or "File"),
              the name of the item, and the content if it's a file (or None for folders).
    """
    tree_structure = []

    try:
        # Get all items in the current folder
        items = os.listdir(folder_path)
    except FileNotFoundError:
        print("Error: The folder path does not exist.")
        return []
    except PermissionError:
        print(f"Error: Permission denied for accessing {folder_path}")
        return []

    for item in items:
        item_path = os.path.join(folder_path, item)
        if os.path.isdir(item_path):
            # If the item is a directory, add it to the structure and recurse
            tree_structure.append(("Folder", item, None))
            tree_structure.extend(generate_folder_tree(item_path, indent + "    "))
        elif os.path.isfile(item_path):
            # If the item is a file, add its name and content
            try:
                with open(item_path, 'r', encoding='utf-8') as file:
                    content = file.read()
                tree_structure.append(("File", item, content))
            except Exception as e:
                tree_structure.append(("File", item, f"Error reading file: {e}"))
        else:
            tree_structure.append(("Unknown", item, None))

    return tree_structure

def display_folder_tree(tree_structure):
    """
    Generates a string representation of the folder tree structure with file contents.

    Parameters:
        tree_structure (list): The folder tree structure generated by generate_folder_tree.

    Returns:
        str: A string representation of the folder tree and contents.
    """
    output = []
    for item_type, name, content in tree_structure:
        if item_type == "Folder":
            output.append(f"[Folder] {name}")
        elif item_type == "File":
            output.append(f"[File] {name}")
            output.append("    Content:")
            output.append("    " + content.replace("\n", "\n    "))
        else:
            output.append(f"[Unknown] {name}")
    return "\n".join(output)

if __name__ == "__main__":
    folder_paths = [r"C:\Users\fridm\Desktop\groupNLPExplanations\pipeline"] #input("Enter the folder path: ") #, "C:\\Users\\fridm\\Documents\\realtime_openai_api\\src"
 #input("Enter the folder path: ")
    tree_output = ''
    for folder_path in folder_paths:
        if os.path.exists(folder_path) and os.path.isdir(folder_path):
            print("Generating Folder Tree and Contents:\n")
            tree_structure = generate_folder_tree(folder_path)
            tree_output = tree_output + display_folder_tree(tree_structure)
            print("The folder tree and contents have been copied to the clipboard.")
        else:
            print("Invalid folder path. Please provide a valid directory.")
        pyperclip.copy(tree_output)
